# Setup
title:               Complications and Extrapolations
tagline:             'there is nothing new under the sun'
description:         'Ruminations on networking, coding, and other technical matters.'
url:                 https://dgh--.github.io/
baseurl:             ""
paginate:            5
permalink:           pretty

# About/contact
author:              
  name:              David Hughes
  url:               https://github.com/dgh--/
  email:             dghughes82@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0

exclude: []

